version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 450M
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movie_db_7n7w?sslmode=require
      SPRING_DATASOURCE_USERNAME: anelisgh
      SPRING_DATASOURCE_PASSWORD: UngYjtAqlrZ7sduNlzfyItqr0atOT5Eq
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      WAIT_HOSTS: postgres:5432
      WAIT_TIMEOUT: 60
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: anelisgh
      POSTGRES_PASSWORD: UngYjtAqlrZ7sduNlzfyItqr0atOT5Eq
      POSTGRES_DB: movie_db_7n7w
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anelisgh -d movie_db_7n7w"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  postgres_data: